export const EPISODE_MIN_MESSAGES = 25;
export const EPISODE_MAX_MESSAGES = 50;
export const EPISODE_MAX_ARTIFACTS_PER_AGENT = 7;
export const EPISODE_ARTIFACT_UNLOCK_AFTER_MESSAGE = 3;
export const EPISODE_MIN_ARTIFACTS_PER_AGENT_BEFORE_DECISION = 4;
